package BO;
// Generated 3-dec-2014 14:49:22 by Hibernate Tools 3.6.0



/**
 * TblCursisten generated by hbm2java
 */
public class TblCursisten  implements java.io.Serializable {


     private Integer id;
     private String voornaam;
     private String naam;
     private int moduleId;

    public TblCursisten() {
    }

    public TblCursisten(String voornaam, String naam, int moduleId) {
       this.voornaam = voornaam;
       this.naam = naam;
       this.moduleId = moduleId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getVoornaam() {
        return this.voornaam;
    }
    
    public void setVoornaam(String voornaam) {
        this.voornaam = voornaam;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public int getModuleId() {
        return this.moduleId;
    }
    
    public void setModuleId(int moduleId) {
        this.moduleId = moduleId;
    }




}


