package BO;
// Generated 3-dec-2014 14:49:22 by Hibernate Tools 3.6.0



/**
 * TblLokalen generated by hbm2java
 */
public class TblLokalen  implements java.io.Serializable {


     private Integer id;
     private String lokaalNaam;

    public TblLokalen() {
    }

    public TblLokalen(String lokaalNaam) {
       this.lokaalNaam = lokaalNaam;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLokaalNaam() {
        return this.lokaalNaam;
    }
    
    public void setLokaalNaam(String lokaalNaam) {
        this.lokaalNaam = lokaalNaam;
    }




}


