package BO;
// Generated 3-dec-2014 14:49:22 by Hibernate Tools 3.6.0



/**
 * TblModules generated by hbm2java
 */
public class TblModules  implements java.io.Serializable {


     private Integer id;
     private String moduleNaam;
     private int lokaalId;
     private int docentId;

    public TblModules() {
    }

    public TblModules(String moduleNaam, int lokaalId, int docentId) {
       this.moduleNaam = moduleNaam;
       this.lokaalId = lokaalId;
       this.docentId = docentId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getModuleNaam() {
        return this.moduleNaam;
    }
    
    public void setModuleNaam(String moduleNaam) {
        this.moduleNaam = moduleNaam;
    }
    public int getLokaalId() {
        return this.lokaalId;
    }
    
    public void setLokaalId(int lokaalId) {
        this.lokaalId = lokaalId;
    }
    public int getDocentId() {
        return this.docentId;
    }
    
    public void setDocentId(int docentId) {
        this.docentId = docentId;
    }




}


